# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jean Mishkin
email: jean@jeanmishkin.com 
description: > # this means to ignore newlines until "baseurl:"
    Jean Mishkin has more than twenty years of experience as an editor helping students write compelling personal essays for college applications, persuasive cover letters and resumés for internships and jobs, scholarly and creative theses, and competitive fellowship applications.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jsnhff.github.io/jean-mishkin/" # the base hostname & protocol for your site
twitter_username: jeanmishkin
twitter_feed: false

# Build settings
markdown: kramdown

gems:
- jekyll-sitemap
